{% set name = "jupyter_bokeh" %}
{% set version = "4.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a33d6ab85588f13640b30765fa15d1111b055cbe44f67a65ca57d3593af8245d

build:
  number: 0
  skip: True # [s390x or  py<38]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - pip
    - python
    - hatchling >=1.5.0
    - hatch-nodejs-version
    - hatch-jupyter-builder >=0.8.2
  run:
    - bokeh >=3,<4
    - ipywidgets >=8,<9
    - python
  run_constrained:
    - jupyterlab >=4.0.0,<5

test:
  imports:
    - jupyter_bokeh
    - jupyter_bokeh.widgets
  commands:
    - pip check
    - jupyter labextension list
    - jupyter labextension list 1>labextensions 2>&1
    - rg -ie "@bokeh/jupyter_bokeh.*OK.*jupyter_bokeh" labextensions
  requires:
    - pip
    - jupyterlab
    - ripgrep

about:
  home: https://pypi.org/project/jupyter-bokeh
  summary: A Jupyter extension for rendering Bokeh content.
  description: |
    A Jupyter extension for rendering Bokeh content within Jupyter.
    See also the separate ipywidgets_bokeh library for support for
    using Jupyter widgets/ipywidgets objects within Bokeh applications.
  license: BSD-3-Clause
  license_family: BSD
  license_file:
    - LICENSE.txt
    - jupyter_bokeh/labextension/static/third-party-licenses.json
  doc_url: https://docs.bokeh.org/en/latest/docs/user_guide/output/jupyter.html
  dev_url: https://github.com/bokeh/jupyter_bokeh

extra:
  recipe-maintainers:
    - bollwyvl
    - philippjfr
    - mattpap
