{% set name = "jupyter_bokeh" %}
{% set version = "3.0.2" %}


package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: 892612078656fa805b5920bd7adf337d1600dc670d0589c3bb46deb8305ad6e0
  - url: https://raw.githubusercontent.com/bokeh/{{ name }}/{{ version }}/LICENSE.txt
    sha256: 88233887fb7842a5ca01dd4c93a4688aaafa76f8a0a6df621fd5a7b2f843bfed

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --install-option="--skip-npm"

requirements:
  host:
    - jupyter-packaging >=0.7.9,<0.8
    - pip
    - python >=3.6
  run:
    - bokeh >=2.0.0
    - ipywidgets >=7.6.0
    - python >=3.6
  run_constrained:
    - jupyterlab >=3,<4

test:
  imports:
    - jupyter_bokeh
    - jupyter_bokeh.nbextension
    - jupyter_bokeh.widgets
  commands:
    - pip check
    - jupyter nbextension list
    - jupyter nbextension list 1>nbextensions 2>&1
    - cat nbextensions | grep "jupyter_bokeh/extension.*enabled"  # [unix]
    - jupyter labextension list
    - jupyter labextension list 1>labextensions 2>&1
    - cat labextensions | grep "@bokeh/jupyter_bokeh.*OK.*jupyter_bokeh"  # [unix]
  requires:
    - pip
    - jupyterlab

about:
  home: https://pypi.org/project/jupyter-bokeh
  summary: A Jupyter extension for rendering Bokeh content.
  license: BSD-3-Clause
  license_file: LICENSE.txt
  dev_url: https://github.com/bokeh/jupyter_bokeh

extra:
  recipe-maintainers:
    - bollwyvl
    - philippjfr
